/* ===========================================================================
   OTOMATİK ÜRETİLMİŞTİR — ELLE DÜZENLEMEYİN
   Üreteç : tools/uret_ozel_program.py
   Kaynak : Özel Program Uygulayan Lise haftalık ders çizelgeleri (TTKB)

   Bu okullarda dersler bir TEMAYA bağlıdır. Okul temasını seçer;
   şubenin dersleri = ortak dersler + ortak tematik dersler + temanın
   kendi dersleri.

   Tema sınırları PDF'in kendi tablo çizgilerinden okunur, tahmin
   edilmez. Elde bulunan eski kaynak JSON'da tema, etiketin denk
   geldiği satırdan itibaren ileri kopyalanmıştı ve sessizce yanlıştı:
   "Havacılık ve Uzayın Temelleri" Yazılım temasına, laboratuvar
   dersleri Havacılık temasına yazılmıştı.
   ======================================================================== */
const OZEL_PROGRAM_TEMALARI = {
    "ozel_program_fen_lisesi": {
        temalar: [
            { id: "bilisim_teknolojileri_ve_yazilim", ad: "Bilişim Teknolojileri ve Yazılım" },
            { id: "havacilik_ve_uzay_teknolojileri", ad: "Havacılık ve Uzay Teknolojileri" },
            { id: "temel_bilimler", ad: "Temel Bilimler" },
        ],
        kota: {"hazirlik": 10, "9": 8, "10": 8, "11": 4, "12": 4},
        ortak: {
            "hazirlik": [
                {"ders": "Programlamaya Giriş ve Algoritma+programlama Dilleri", "saat": 4, "saatSecenekleri": [4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                {"ders": "Temel Elektrik-elektronik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                {"ders": "Tümleşik Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
            ],
        },
        dersler: {
            "bilisim_teknolojileri_ve_yazilim": {
                "hazirlik": [
                    {"ders": "Sayısal Elektronik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "9": [
                    {"ders": "Bilgisayarlı Devre Simülasyonu ve Baskı Devre Tasarımı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Mikrodenetleyiciler ve Uygulamaları", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Nesne Tabanlı Programlama", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "10": [
                    {"ders": "Veri Bilimi", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Robotik Uygulamaları", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ağ Teknolojileri ve Nesnelerin İnterneti", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "havacilik_ve_uzay_teknolojileri": {
                "hazirlik": [
                    {"ders": "Havacılık ve Uzayın Temelleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "9": [
                    {"ders": "Sayısal Elektronik ve Mikrodenetleyiciler", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Mekaniğin Temelleri", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Meteoroloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "temel_bilimler": {
                "9": [
                    {"ders": "Fizik Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Kimya Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoloji Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Temel Bilimlerde Bilişim Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
        secilebilir: {
            "havacilik_ve_uzay_teknolojileri": {
                "10": [
                    {"ders": "Robotik Uygulamaları", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilgisayar Destekli Tasarım ve Modelleme", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Havacılık Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Havacılık Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Seyrüsefer", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İtki Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uzay Teknolojileri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Seyrüsefer", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İtki Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uzay Teknolojileri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Simülasyon Teknolojileri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "temel_bilimler": {
                "10": [
                    {"ders": "Fizik Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Kimya Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoloji Laboratuvarı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Temel Bilimlerde Bilişim Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Matematik", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Geleceğin Enerji Sistemleri", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İstatistik", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoteknoloji", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Anatominin Temelleri", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Epidemiyoloji", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "Sağlık Hizmetleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Temel Bilimlerde Bilişim Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Geleceğin Enerji Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İstatistik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoteknoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Anatominin Temelleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Epidemiyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Sağlık Hizmetleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyokimya", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Moleküler Biyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Optimizasyon", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Polimer Kimyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Nükleer Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tıp Bilimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İleri Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Temel Bilimlerde Bilişim Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Geleceğin Enerji Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İstatistik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoteknoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Anatominin Temelleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Epidemiyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Sağlık Hizmetleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyokimya", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Moleküler Biyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Optimizasyon", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Polimer Kimyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Nükleer Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tıp Bilimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İleri Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Genetik Bilimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "bilisim_teknolojileri_ve_yazilim": {
                "11": [
                    {"ders": "Yapay Zekâ ve Makine Öğrenmesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilgisayar Mimarisi ve İşletim Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siber Güvenlik ve Kriptoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Yapay Zekâ ve Makine Öğrenmesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilgisayar Mimarisi ve İşletim Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siber Güvenlik ve Kriptoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yazılım Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
    },
    "ozel_program_sosyal_lisesi": {
        temalar: [
            { id: "medya_ve_iletisim", ad: "Medya ve İletişim" },
            { id: "siyaset_bilimi_ve_uluslararasi_iliskiler", ad: "Siyaset Bilimi ve Uluslararası İlişkiler" },
            { id: "iktisat_ve_isletme", ad: "İktisat ve İşletme" },
            { id: "edebiyat_tarih_ve_kultur", ad: "Edebiyat, Tarih ve Kültür" },
            { id: "yabanci_diller", ad: "Yabancı Diller" },
        ],
        kota: {"hazirlik": 6, "9": 6, "10": 8, "11": 8, "12": 8},
        ortak: {
            "hazirlik": [
                {"ders": "Medya ve İletişimin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                {"ders": "Siyaset Biliminin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                {"ders": "Ekonominin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
            ],
        },
        dersler: {
            "medya_ve_iletisim": {
                "9": [
                    {"ders": "İletişim Bilimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Hitabet ve Belagat Sanatı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "10": [
                    {"ders": "Haber Yazma Teknikleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Temel Fotoğrafçılık", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yeni Medya", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Halkla İlişkiler ve Reklamcılık", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "siyaset_bilimi_ve_uluslararasi_iliskiler": {
                "9": [
                    {"ders": "Kamu Yönetimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Hukuka Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uluslarası İlişkilere Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "iktisat_ve_isletme": {
                "9": [
                    {"ders": "İktisada Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İktisadi Olaylar ve Dönemler Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Genel İşletme", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "edebiyat_tarih_ve_kultur": {
                "9": [
                    {"ders": "Dil Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Edebiyatı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medeniyet Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
        secilebilir: {
            "yabanci_diller": {
                "9": [
                    {"ders": "İkinci Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "Almanca", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Üçüncü Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Drama Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Çeviri Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Metin Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Yaratıcı Yazma", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "10": [
                    {"ders": "İkinci Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "Almanca", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Üçüncü Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Drama Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Çeviri Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Metin Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Yaratıcı Yazma", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Turizm ve Rehberlik Bilgisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "İkinci Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "Almanca", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Üçüncü Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Drama Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Çeviri Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Metin Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Yaratıcı Yazma", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Turizm ve Rehberlik Bilgisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "İkinci Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "Almanca", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Üçüncü Yabancı Dil", "saat": 2, "saatSecenekleri": [2, 3, 4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Drama Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Çeviri Uygulamaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Metin Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Yaratıcı Yazma", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Turizm ve Rehberlik Bilgisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "siyaset_bilimi_ve_uluslararasi_iliskiler": {
                "10": [
                    {"ders": "Anayasal Düzen", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasi Tarih: Sömürgecilik ve Sonrası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasal Düşünceler Tarihi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Demokrasi Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Felsefesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Farklı Ülkelerde Yönetim ve Demokrasi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Siyasi Tarih: Sömürgecilik ve Sonrası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasal Düşünceler Tarihi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Demokrasi Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Felsefesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Farklı Ülkelerde Yönetim ve Demokrasi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Politik Ekonomi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyaset Sosyolojisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Dünyası Politikaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Millî Güç Unsurları ve Jeopolitik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasetname Okumaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uluslararası Örgütler", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Dış Politikası", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uluslararası Hukuk", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Siyaset Sosyolojisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Dünyası Politikaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Millî Güç Unsurları ve Jeopolitik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasetname Okumaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uluslararası Örgütler", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Dış Politikası", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Uluslararası Hukuk", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ülke ve Bölge Çalışmaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "iktisat_ve_isletme": {
                "10": [
                    {"ders": "Yönetim ve Organizasyon", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tedarik Zincirleri ve Lojistik", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İktisatta Mikro ve Makro Yaklaşımlar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye Ekonomisi: İktisat Politikaları, Dönemler, Göstergeler", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Matematiksel İktisat", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Türkiye Ekonomisi: İktisat Politikaları, Dönemler, Göstergeler", "saat": 3, "saatSecenekleri": [3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Matematiksel İktisat", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İnsan Kaynakları ve Yönetimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İktisadi Düşünceler Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Marka Yönetimi ve Pazarlama", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk İslam İktisat Tarihi ve Düşüncesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye'nin Kalkınma Serüveni", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "İnsan Kaynakları ve Yönetimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İktisadi Düşünceler Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Marka Yönetimi ve Pazarlama", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk İslam İktisat Tarihi ve Düşüncesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye'nin Kalkınma Serüveni", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ekonomik Göstergelerin Analizi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Yönetim", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "edebiyat_tarih_ve_kultur": {
                "10": [
                    {"ders": "Türk Halk Bilimi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dinler Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "İHL Meslek Dersleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarihe Yön Verenler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ülkeler Coğrafyası", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yaratıcı Yazarlık Çalışmaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Ülkeler Coğrafyası", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yaratıcı Yazarlık Çalışmaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İklim, Çevre ve Yenilikçi Çözümler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilim Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dünya Edebiyatı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk İslam Sanatları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilim, Teknoloji ve Sosyal Değişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Sosyolojisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dijital Sanatlar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Bilişim Teknolojileri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Türk İslam Sanatları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Bilim, Teknoloji ve Sosyal Değişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Sosyolojisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dijital Sanatlar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Bilişim Teknolojileri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Sosyal Antropoloji", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Edebî Metinlerinde Üslup İncelemeleri", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Karşılaştırmalı Kültür Çalışmaları", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Karşılaştırmalı Edebiyat", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "medya_ve_iletisim": {
                "11": [
                    {"ders": "Haber Yazma Teknikleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Temel Fotoğrafçılık", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yeni Medya", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Halkla İlişkiler ve Reklamcılık", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İçerik Üretim Teknikleri", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Görsel İletişim Tasarımı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya Endüstrisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya Hukuku ve Etik", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İletişim Sosyolojisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dezenformasyon ve Toplum", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya ve Sanat", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Gazeticiliği", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medyada İçerik Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Halkla İlişkiler ve Reklamcılık", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İçerik Üretim Teknikleri", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Görsel İletişim Tasarımı", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya Endüstrisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya Hukuku ve Etik", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İletişim Sosyolojisi", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Dezenformasyon ve Toplum", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya ve Sanat", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Gazeticiliği", "saat": 2, "saatSecenekleri": [2, 3], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medyada İçerik Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasal İletişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
    },
    "ozel_program_hazirlik_anadolu_lisesi": {
        temalar: [
            { id: "temel_bilimler", ad: "Temel Bilimler" },
            { id: "sosyal_bilimler", ad: "Sosyal Bilimler" },
        ],
        kota: {"hazirlik": 4, "9": 6, "10": 6, "11": 8, "12": 8},
        ortak: {
        },
        dersler: {
            "temel_bilimler": {
                "hazirlik": [
                    {"ders": "Tümleşik Bilimler", "saat": 4, "saatSecenekleri": [4], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "sosyal_bilimler": {
                "hazirlik": [
                    {"ders": "Sosyal Bilim Çalışmaları", "saat": 4, "saatSecenekleri": [4], "atananBrans": "Felsefe", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "9": [
                    {"ders": "Sosyal Bilim Çalışmaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Felsefe", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Edebiyat Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
        secilebilir: {
            "temel_bilimler": {
                "9": [
                    {"ders": "Tümleşik Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Fizik Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Kimya Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoloji Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "10": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Fizik Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Kimya Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoloji Laboratuvarı", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Fen Bilimleri Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Matematik Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Matematik", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Fen Bilimleri Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Matematik Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Matematik", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İstatistik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Optimizasyon", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Geleceğin Enerji Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Nükleer Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoteknoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Anatominin Temelleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Epidemiyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Sağlık Hizmetleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Moleküler Biyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyokimya", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Polimer Kimyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Fen Bilimleri Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Matematik Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Matematik", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Finansal Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Veri Analizi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İstatistik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Optimizasyon", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Geleceğin Enerji Sistemleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Nükleer Bilimler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyoteknoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Anatominin Temelleri", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Epidemiyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "Sağlık Hizmetleri", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Moleküler Biyoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Biyokimya", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Polimer Kimyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Malzeme Bilimi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "İleri Matematik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Genetik Bilimine Giriş", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
            "sosyal_bilimler": {
                "10": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Edebiyat Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ekonominin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya ve İletişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yaratıcı Yazarlık Çalışmaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye'nin Kalkınma Serüveni", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Millî Güç Unsurları ve Jeopolitik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasi Tarih:sömürgecilik ve Sonrası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Demokrasi Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "11": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Edebiyat Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ekonominin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya ve İletişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yaratıcı Yazarlık Çalışmaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye'nin Kalkınma Serüveni", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Millî Güç Unsurları ve Jeopolitik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasi Tarih:sömürgecilik ve Sonrası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Demokrasi Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyaset Sosyolojisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medeniyet Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarihe Yön Verenler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Felsefesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ülkeler Coğrafyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Sosyal Antropoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Proje Tabanlı Sosyal Araştırma", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
                "12": [
                    {"ders": "Yabancı Dilde Akademik Çalışmalar", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Edebiyat Uygulamaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ekonominin Temel Kavramları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medya ve İletişim", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Yaratıcı Yazarlık Çalışmaları", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türkiye'nin Kalkınma Serüveni", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Millî Güç Unsurları ve Jeopolitik", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyasi Tarih:sömürgecilik ve Sonrası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Türk Demokrasi Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Siyaset Sosyolojisi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Medeniyet Tarihi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarihe Yön Verenler", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Tarih Felsefesi", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Ülkeler Coğrafyası", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Sosyal Antropoloji", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                    {"ders": "Proje Tabanlı Sosyal Araştırma", "saat": 2, "saatSecenekleri": [2], "atananBrans": "— Branş Atanmadı —", "kategori": "TEMATİK ALAN DERSLERİ", "isAtolye": false},
                ],
            },
        },
    }
};
